### ISSUE TITLE
 Incompatibility with hashing package

### ISSUE THREAD

**Issue by miha-pece** [xor-gate/syncthing-macosx#107]
I upgraded sync 1.4.0 with brew service, of course, I also installed sync through homebrew. But now app doesn't want to start, something is apparently wrong with hash package. I'm on 2009 Mac Pro with High Sierra.

_Partial terminal response on manual run (full text in file):

Crash due to illegal instruction detected. This is most likely due to a CPU 
incompatibility with the high performance hashing package. Switching to the 
 standard hashing package instead. Please report this issue at:_              
                                                                            
   https://github.com/syncthing/syncthing/issues                             
[syncthing-error-hash.txt](https://github.com/syncthing/syncthing-macos/files/4380801/syncthing-error-hash.txt)

**Comment by calmh** [comment]
This is because homebrew builds things with Go 1.14, which unfortunately wasn't compatible with the CPU in your older Mac. Go 1.14.1 fixed this, and at some point homebrew will probably redo their builds. But this isn't a problem that can be fixed neither here nor in syncthing/syncthing. You can use one of the Syncthing downloads from syncthing.net in the meantime.
