### ISSUE TITLE
Syncthing executable background process CPU consumption

### ISSUE THREAD

**Issue by jil24** [xor-gate/syncthing-macosx#11]
The UI should allow reprioritizing the syncthing process so that it does not interfere with UI responsiveness.

Also should support setting the maximum number of threads to spawn with the GOMAXPROCS environment variable

**Comment by xor-gate** [comment]
I have no clue what you mean with reprioritising the syncthing process. It just starts as a background child process of the syncthing-macosx bundle and there is no interfere with UI responsiveness. 

Currently it is not possible to pass environment variables to the child process.

**Comment by jil24** [comment]
I meant something equivalent to spawning with the command "nice -n 20 syncthing" so that other processes get priority. Syncthing doesn't as of now cause issues with UI responsiveness per se, but it does seem to slow down performing other computationally expensive tasks on the machine, when sync should probably be the least important thing going on.

**Comment by xor-gate** [comment]
Yeah now I understand. You mean in context of Operating System UI responsiveness. The NSTask class has a qualityOfService property which is used for this purpose instead of chaining in a `nice` call.

Note to self:
https://developer.apple.com/reference/foundation/nstask/1415794-qualityofservice?language=objc
https://developer.apple.com/library/content/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/PrioritizeWorkAtTheTaskLevel.html
