### ISSUE TITLE
Automatic upgrades in GUI

### ISSUE THREAD

**Issue by tohvanah** [xor-gate/syncthing-macosx#122]
Just getting started today for my first time with a fresh install via syncthing-macos. In the web GUI, why does it state "Unavailable/Disabled by administrator or maintainer" under **Automatic upgrades**? I reviewed the advanced options, and the settings seem default. What am I missing?

**Comment by xor-gate** [comment]
Good question, 

Syncthing for macOS actually are two applications, the Syncthing (daemon) and the macOS application/tray icon.

What it actually means is Syncthing daemon will not auto-update because it is bundled with the macOS application bundle which disables the syncthing auto-updating mechanism. When syncthing daemon auto-updates it changes the bundle content and macOS can possible mark it is being tampered with as it is digital signed for correctness. So this means for the end user to wait the bundle is updated with the new syncthing daemon which will lag maximum a few weeks behind the Syncthing release (on best effort basis). The bundle automatically checks every 24h if there is an update and will notify the user there is an update and you can then enable automatic background updates.

Hope this clears things up.

**Comment by tohvanah** [comment]
Ok, that does clear it up. I didn't realize the macOS app was being updated frequently with newer versions of Syncthing bundled. I was confused by previous discussions of the binary being outside of the app bundle, but see things have changed recently. I'm glad there's an update mechanism in place, and a few weeks lag is fine. 👍

**Comment by xor-gate** [comment]
Yes the confusion is indeed because the old behaviour was the syncthing binary outside the app which also has its drawbacks with disk permissions.
