### ISSUE TITLE
Any plans to update to 1.18.2?

### ISSUE THREAD

**Issue by kapitainsky** [xor-gate/syncthing-macosx#165]
syncthing v1.18.2 has been released 24 days ago and syncthing-macos has not been updated yet.

Are there any plans to do it? Or things changed and there is other way to update.

**Comment by xor-gate** [comment]
Hi @kapitainsky, sorry for the release delay I was actually waiting to bundle the upcoming v1.18.3. I already prepared the v1.18.2 but there is currently something wrong with the release build server. I will let you know in this issue when the new release is out (hopefully before the end of this weekend).

Kind regards,
Jerry

@calmh it seems the macos xcode builder is broken because of some software package needs updating. Could you have a look <https://build.syncthing.net/buildConfiguration/SyncthingMacOS_BuildReleaseDmg/111756?buildTab=log&focusLine=139&linesState=133>?

**Comment by kapitainsky** [comment]
ok this is not the most important especially that upcoming 1.18.3 will be released. No issue with skipped 1.18.2 - at least as I can read release notes nothing critical. But good to know that this project is not abandoned.

**Comment by kapitainsky** [comment]
so now we can expect 1.18.3 directly?

**Comment by xor-gate** [comment]
The release is out, use the check for update button for direct update (or else you must wait until the update channel is checked)
<img width="512" alt="Screenshot 2021-10-06 at 19 24 32" src="https://user-images.githubusercontent.com/1050166/136253342-f13b5d04-c4c2-4a9f-b480-82522c564acc.png">

**Comment by kapitainsky** [comment]
Thank you for quick action! All works perfectly.
