### ISSUE TITLE
Are updates no longer provided?

### ISSUE THREAD

**Issue by timkgh** [xor-gate/syncthing-macosx#189]
Check for updates doesn't show any new versions. Same in Homebrew. But v1.23.1 of Synchting was released 2 weeks ago.

**Comment by xor-gate** [comment]
Hi @timkgh, I didn't catch up on life and I have missed the update. Sorry for the delay.

Fixed in https://github.com/syncthing/syncthing-macos/commit/536c1afa855b8d7a992fdf56b1a07064e1198d92 

The auto-updater needs ~10 minutes to catch up, when you don't want to wait for the auto-update check: Click on status bar icon -> About -> Check for updates. Or install by hand (which is boring). 

See also [github.com/syncthing/syncthing-macos/releases/tag/v1.23.1-1](https://github.com/syncthing/syncthing-macos/releases/tag/v1.23.1-1)
