### ISSUE TITLE
Currently releases are not trusted by Gatekeeper (payed apple developer account)

### ISSUE THREAD

**Issue by dipenpatel235** [xor-gate/syncthing-macosx#27]
hello..
i am interested to used this app.
so if i paid to apple for account so can u help me to published on store with apples security rule ?

Thanks

**Comment by xor-gate** [comment]
Hi @dipenpatel235 thank you for your interest, i'm not 100% sure if apple will accept this as it doesn't follow the GUI guideliness and it ships a binary which is executed. For developer access this costs 99 dollar a year.

**Comment by xor-gate** [comment]
I remember now there are three options:

1. Use the app and allow untrusted (which is the current situation)
2. Use the app distributed and signed by me with a paid mac account (verified)
3. Use the app distributed and signed with the mac app store (difficult)

Option 2 is more easy because it allows how the current app is build and doesn't need any verification from apple (GUI guidelines, App Store guidelines). Option 3 is hard because I need to satisfy the GUI guidelines and App Store guidelines (see https://developer.apple.com/app-store/review/guidelines/)

**Comment by dipenpatel235** [comment]
ok.
i have no issue to choose option 2.
can u please tell me which info u required for option  2?
and using option2 it will not show untrusted to end user right ?

give me your email or skype so i can provide you account related info if u required.

Thanks

**Comment by jibinkumar** [comment]
@xor-gate That would be great to see this (verified)!

**Comment by ssbarnea** [comment]
Please start signing it ASAP, that's not only a nice thing to have but a really essential feature. Even those that do not publish apps using AppStore do have to sign apps. Requiring people to install unsigned apps is like Windows app developers asking you to disable antivirus before installing thei apps ;)

**Comment by xor-gate** [comment]
@virusman will take care of this as soon as a new release will happen. He is now also a project contributor.

**Comment by xor-gate** [comment]
Should be fine, feel free to comment. There is still a pending issue when syncthing upgrades itself and the bundle signature changes for Gatekeeper. See the new issue #37.
