### ISSUE TITLE
Is there a way to automate api configuration step?

### ISSUE THREAD

**Issue by jibinkumar** [xor-gate/syncthing-macosx#31]
"The only necessary configuration is to set the api key which can be found in the web interface."
We are interested in automating the api configuration step. Can you please advice on how this can be done?

**Comment by xor-gate** [comment]
The API key can currently be found in the XML configuration file (default path is `$HOME/Library/Application Support/Syncthing`). Reading the XML file is already code for but not integrated yet to "autoconfigure/load from xml". See https://github.com/xor-gate/syncthing-macosx/blob/b9e9bac1339d72199adf7f6fc406cf505f49087d/syncthing/XGSyncthing.m#L135-L174. But there is a discussion going on in the future the stored API key in de XML file is unusable because it will be hashed https://forum.syncthing.net/t/proposal-for-hashing-api-keys/7493.

**Comment by virusman** [comment]
This should now work in #36
