### ISSUE TITLE
Update unable to complete

### ISSUE THREAD

**Issue by ChristianMenzel** [xor-gate/syncthing-macosx#85]
Try to update from 0.14.49-1 to 0.14.52 
on Sierra 10.12.6

`com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit`

Message: 
Update Error!
An error occurred while extracting the archive. ...

**Comment by Vykook** [comment]
Same on Mojave (10.14.1 (18B75))

**Comment by xor-gate** [comment]
Hi all,

You need to manually install the latest version because the application bundle is signed with a new/different certificate.

It is impossible to fix this as it is by the design of Sparkle autoupdater. However I put a big notice in de release changelog but background updates don’t show it.

Hopefully this will be the past time we need to change the siging certificate.

Kind regards,
Jerry

**Comment by xor-gate** [comment]
For more info see: https://github.com/syncthing/syncthing-macos/releases/tag/v0.14.52-1
