### ISSUE TITLE
request version bump now that 1.0.0 is available upstream

### ISSUE THREAD

**Issue by sneak** [xor-gate/syncthing-macosx#88]

**Comment by xor-gate** [comment]
Hi @sneak, I lived under a rock for a few days because of work. Hopefully I will create some time next week. Thanks for poking around here!

**Comment by xor-gate** [comment]
@calmh i forgot the sparkle/bundle version string wrapped because the major version was never used. I have updated the appcast.xml generator, could you deploy it into production?

**Comment by calmh** [comment]
I’ll check it out mañana.

On 12 Jan 2019, at 17:56, Jerry Jacobs <notifications@github.com<mailto:notifications@github.com>> wrote:


@calmh<https://github.com/calmh> i forgot the sparkle/bundle version string wrapped because the major version was never used. I have updated the appcast.xml generator, could you deploy it into production?

**Comment by calmh** [comment]
I've updated the appcast generator
